apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-repo'
    targetRevision: main
    path: manifests  # or helm-chart if using Helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flask-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
